//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixCustom {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoenixCustom.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   TestPhoenixRuleDescription に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0000_Description {
            get {
                return ResourceManager.GetString("PH0000_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestPhoenixRule に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0000_Name {
            get {
                return ResourceManager.GetString("PH0000_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TestPhoenixRuleResolution に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0000_Resolution {
            get {
                return ResourceManager.GetString("PH0000_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   戻り値がnullではないメソッドの結果がnullと比較された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Description {
            get {
                return ResourceManager.GetString("PH0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidNonNullMethodResultComparedByNull に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Name {
            get {
                return ResourceManager.GetString("PH0001_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}メソッドの結果をnullと比較しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Resolution {
            get {
                return ResourceManager.GetString("PH0001_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数が使用されずに再代入されている場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Description {
            get {
                return ResourceManager.GetString("PH0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidReasignLocalWithoutUsed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Name {
            get {
                return ResourceManager.GetString("PH0002_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式の結果{0}が使用されていません。変数へ格納しないように修正するか、式を削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Resolution {
            get {
                return ResourceManager.GetString("PH0002_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能な引数が複数回使用された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Description {
            get {
                return ResourceManager.GetString("PH0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiEvaluateDelayableParameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Name {
            get {
                return ResourceManager.GetString("PH0003_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目で使用された遅延評価可能な引数が再度使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Resolution {
            get {
                return ResourceManager.GetString("PH0003_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能なローカル変数が複数回使用された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Description {
            get {
                return ResourceManager.GetString("PH0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiEvaluateDelayableLocal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Name {
            get {
                return ResourceManager.GetString("PH0004_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目で使用された遅延評価可能な変数が再度使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Resolution {
            get {
                return ResourceManager.GetString("PH0004_Resolution", resourceCulture);
            }
        }
    }
}
