//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhoenixCustom {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhoenixCustom.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   戻り値がnullではないメソッドの結果がnullと比較された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Description {
            get {
                return ResourceManager.GetString("PH0001_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidNonNullMethodResultComparedByNull に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Name {
            get {
                return ResourceManager.GetString("PH0001_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}メソッドの結果をnullと比較しません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0001_Resolution {
            get {
                return ResourceManager.GetString("PH0001_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   変数が使用されずに再代入されている場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Description {
            get {
                return ResourceManager.GetString("PH0002_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidReasignLocalWithoutUsed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Name {
            get {
                return ResourceManager.GetString("PH0002_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   式の結果{0}が使用されていません。変数へ格納しないように修正するか、式を削除します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0002_Resolution {
            get {
                return ResourceManager.GetString("PH0002_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能な引数が複数回使用された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Description {
            get {
                return ResourceManager.GetString("PH0003_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiEvaluateDelayableParameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Name {
            get {
                return ResourceManager.GetString("PH0003_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能な引数{0}が{1}行目で使用された後に再度使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0003_Resolution {
            get {
                return ResourceManager.GetString("PH0003_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能なローカル変数が複数回使用された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Description {
            get {
                return ResourceManager.GetString("PH0004_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiEvaluateDelayableLocal に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Name {
            get {
                return ResourceManager.GetString("PH0004_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   遅延評価可能な変数{0}が{1}行目で使用された後に再度使用されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0004_Resolution {
            get {
                return ResourceManager.GetString("PH0004_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IEnumerable&lt;T&gt;型を返却するメソッドが遅延評価可能なインスタンスを返却しない場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0005_Description {
            get {
                return ResourceManager.GetString("PH0005_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   EnumerateMethodShouldBeDelayed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0005_Name {
            get {
                return ResourceManager.GetString("PH0005_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IEnumerable&lt;T&gt;型を返却するメソッドの戻り値が遅延評価可能なように実装します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0005_Resolution {
            get {
                return ResourceManager.GetString("PH0005_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティを複数回読み出している場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0006_Description {
            get {
                return ResourceManager.GetString("PH0006_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiGetProperty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0006_Name {
            get {
                return ResourceManager.GetString("PH0006_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   プロパティの評価結果をキャッシュします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0006_Resolution {
            get {
                return ResourceManager.GetString("PH0006_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PerformanceCliticalMethodとして指定されたメソッドが複数回使用された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0007_Description {
            get {
                return ResourceManager.GetString("PH0007_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiEvaluatePerformanceCriticalMethod に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0007_Name {
            get {
                return ResourceManager.GetString("PH0007_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   評価結果をキャッシュします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0007_Resolution {
            get {
                return ResourceManager.GetString("PH0007_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数回キャストされた場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0008_Description {
            get {
                return ResourceManager.GetString("PH0008_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidDoubleCast に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0008_Name {
            get {
                return ResourceManager.GetString("PH0008_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目で処理したキャストが再度行われています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0008_Resolution {
            get {
                return ResourceManager.GetString("PH0008_Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   同じ結果になるメソッドが複数回呼び出された場合を検出する に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0009_Description {
            get {
                return ResourceManager.GetString("PH0009_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AvoidMultiCalculatePureMethod に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0009_Name {
            get {
                return ResourceManager.GetString("PH0009_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}行目で処理した{1}メソッドが再度計算されています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string PH0009_Resolution {
            get {
                return ResourceManager.GetString("PH0009_Resolution", resourceCulture);
            }
        }
    }
}
